import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */
import {
  marvelDoodleTshirt,
  blackPantherHoodie,
  lokiMug,
  captMarvelTshirt,
  blackPantherKeychain,
  marvelWomen,
  infinityWarHoodie,
  ironManKeychain,
  fullSleevesThor,
  captAmericaKeychain,
  spidermanHoodie,
  drStrangeMug,
  avengersMug,
  logoTshirt,
  fullSleevesArcReactor,
} from "../../Assets/index";

export const products = [
  {
    _id: uuid(),
    name: "Grey T-shirt",
    description: "Casual grey colour t-shirt with marvel heroes doodle.",
    originalPrice: 1500,
    hasOffer: true,
    hasDiscount: true,
    discountPrice: 900,
    badgeMessage: "summer sale",
    imageSrc: marvelDoodleTshirt,
    inStock: true,
    fastDelivery: true,
    categoryName: "tshirt",
    ratings: 4.5,
  },
  {
    _id: uuid(),
    name: "Black Panther Hoodie",
    description: "Black fitted hoodie with printed chain.",
    originalPrice: 2500,
    hasOffer: true,
    hasDiscount: true,
    discountPrice: 1500,
    badgeMessage: "new arrival",
    imageSrc: blackPantherHoodie,
    inStock: true,
    fastDelivery: true,
    categoryName: "hoodie",
    ratings: 5,
  },
  {
    _id: uuid(),
    name: "Loki mug",
    description: "Green and yellow mug with text",
    originalPrice: 600,
    hasOffer: true,
    hasDiscount: true,
    discountPrice: 400,
    badgeMessage: "summer sale",
    imageSrc: lokiMug,
    inStock: true,
    fastDelivery: true,
    categoryName: "mug",
    ratings: 4.3,
  },
  {
    _id: uuid(),
    name: "Captain Marvel T-shirt",
    description: "Captain Marvel and Flerken tshirt",
    originalPrice: 1000,
    hasOffer: true,
    hasDiscount: true,
    discountPrice: 900,
    badgeMessage: "trending",
    imageSrc: captMarvelTshirt,
    inStock: true,
    fastDelivery: true,
    categoryName: "tshirt",
    ratings: 4.4,
  },
  {
    _id: uuid(),
    name: "Black Panther keychain",
    description: "Black fitted hoodie with printed chain.",
    originalPrice: 400,
    hasOffer: false,
    hasDiscount: false,
    discountPrice: 400,
    badgeMessage: "summer sale",
    imageSrc: blackPantherKeychain,
    inStock: true,
    fastDelivery: true,
    categoryName: "keychain",
    ratings: 3.9,
  },
  {
    _id: uuid(),
    name: "Marvels' woman T-shirt",
    description: "She's got help tshirt",
    originalPrice: 1100,
    hasOffer: true,
    hasDiscount: true,
    discountPrice: 900,
    badgeMessage: "new arrival",
    imageSrc: marvelWomen,
    inStock: true,
    fastDelivery: true,
    categoryName: "tshirt",
    ratings: 4.0,
  },
  {
    _id: uuid(),
    name: "Full sleeves Tshirt",
    description: "Arc reactor grey color tshirt",
    originalPrice: 1100,
    hasOffer: true,
    hasDiscount: true,
    discountPrice: 900,
    badgeMessage: "summer sale",
    imageSrc: fullSleevesArcReactor,
    inStock: true,
    fastDelivery: true,
    categoryName: "full sleeves",
    ratings: 4.2,
  },
  {
    _id: uuid(),
    name: "Infinity War hoodie",
    description: "Full sleeves hoodie",
    originalPrice: 4000,
    hasOffer: true,
    hasDiscount: true,
    discountPrice: 3000,
    badgeMessage: "trending",
    imageSrc: infinityWarHoodie,
    inStock: true,
    fastDelivery: true,
    categoryName: "hoodie",
    ratings: 4.8,
  },
  {
    _id: uuid(),
    name: "Thor full sleeves T-shirt",
    originalPrice: 950,
    description: "Thor full sleeves tshirt ",
    hasOffer: false,
    hasDiscount: false,
    discountPrice: 950,
    badgeMessage: "",
    imageSrc: fullSleevesThor,
    inStock: true,
    fastDelivery: true,
    categoryName: "full sleeves",
    ratings: 4.0,
  },
  {
    _id: uuid(),
    name: "Iron Man keychain",
    description: "Iron Man keychain",
    originalPrice: 400,
    hasOffer: true,
    hasDiscount: true,
    discountPrice: 200,
    badgeMessage: "summer sale",
    imageSrc: ironManKeychain,
    inStock: true,
    fastDelivery: true,
    categoryName: "keychain",
    ratings: 3.9,
  },
  {
    _id: uuid(),
    name: "Capt. America keychain",
    description: "Captain America keychain",
    originalPrice: 400,
    hasOffer: true,
    hasDiscount: true,
    discountPrice: 200,
    badgeMessage: "trending",
    imageSrc: captAmericaKeychain,
    inStock: true,
    fastDelivery: true,
    categoryName: "keychain",
    ratings: 4.5,
  },
  {
    _id: uuid(),
    name: "Spiderman hoodie",
    description: "Spiderman logo hoodie",
    originalPrice: 3500,
    hasOffer: false,
    hasDiscount: false,
    discountPrice: 3500,
    badgeMessage: "summer sale",
    imageSrc: spidermanHoodie,
    inStock: true,
    fastDelivery: true,
    categoryName: "hoodie",
    ratings: 4.5,
  },
  {
    _id: uuid(),
    name: "Doctor Strange mug",
    description: "Dr Strange comics mug",
    originalPrice: 600,
    hasOffer: true,
    hasDiscount: true,
    discountPrice: 400,
    badgeMessage: "summer sale",
    imageSrc: drStrangeMug,
    inStock: true,
    fastDelivery: true,
    categoryName: "mug",
    ratings: 2.8,
  },
  {
    _id: uuid(),
    name: "Avengers mug",
    description: "White printed avengers cup",
    originalPrice: 600,
    hasOffer: false,
    hasDiscount: false,
    discountPrice: 600,
    badgeMessage: "",
    imageSrc: avengersMug,
    inStock: true,
    fastDelivery: true,
    categoryName: "mug",
    ratings: 1.9,
  },
  {
    _id: uuid(),
    name: "Black T-shirt",
    description: "Marvel logo black color tshirt",
    originalPrice: 900,
    hasOffer: true,
    hasDiscount: true,
    discountPrice: 650,
    badgeMessage: "out of stock",
    imageSrc: logoTshirt,
    inStock: false,
    fastDelivery: false,
    categoryName: "tshirt",
    ratings: 3.1,
  },
];
